### PR TITLE
Prepare for Renovate with reusable workflows

### PR DESCRIPTION
**Pull request by ghostwriter**
|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

Adding Renovate to Laminas, Mezzio repositories. https://gist.github.com/weierophinney/49ca8ae2b916d898dd3d4162b26ff41b

- Configure minimum supported PHP version
- Update composer dependencies
- Update to reusable `Continuous Integration` workflow
- Update to reusable `Automatic Releases` workflow

### CODE REVIEW

**Comment by ghostwriter** [comment]
Ready for review @Ocramius 

@boesing will this [`.laminas-ci.json`](https://github.com/laminas/laminas-cache-storage-deprecated-factory/pull/2/commits/e4ff1d97b68de36463eb0bfdf16bfa217f828c3c) be enough or is it too much? 

CI was not passing in this repo prior to this PR.

**Review by Ocramius — APPROVED** [review]
@ghostwriter this is more than enough, especially for a deprecated package, thanks! 

Releasing as `1.0.1` just to see if tagging works (seems to be a bit stuck)

**Comment by Ocramius** [comment]
Indeed, release workflow crashed :shrug:

**Comment by ghostwriter** [comment]
the response `CreateReleaseThroughApiCall` got back from GitHub is missing the key `html_url`.

https://github.com/laminas/automatic-releases/blob/53605874c048fd28a087662d173415be3230920f/src/Github/Api/V3/CreateReleaseThroughApiCall.php#L39-L71

**Comment by Ocramius** [comment]
Yeah, usually means that an error was produced.

Potentially something else wrong, but the logs are a bit cryptic :D

**Pull request merged**
