### PR TITLE
Add support for PHP 8.3

### PR DESCRIPTION
**Pull request by glo71317**
|    Q          |   A
|-------------- | ------
| New Feature   | yes

### Description

This adds support for PHP 8.3.

### CODE REVIEW

**Comment by glo71317** [comment]
Unable to locate following packages for php 8.3
Screenshot 2023-10-12 at 4 33 04 PM
Have to see what can do for fixing above errors

**Comment by glo71317** [comment]
@froschdesign Can you please suggest about above errors?

**Comment by FabianKoestring** [comment]
Any plans of integrating this in the near future?

**Comment by boesing** [comment]
Thanks, @glo71317 !

**Pull request merged**
